/*
 * FILE : md5_test.c
 *
 * Test the md5() function.
 *
 * NOTE:You can compare the md5 hashes generated by this
 * program to the md5sum program.  To get the hash of a
 * string using md5sum try:
 *
 * $ echo -n "Hello World" | md5sum
 *
 * For strings less than 56 bytes, should give you same
 * results as:
 *
 * $ ./md5_test "Hello World"
 *
 * AUTHOR : Brandon Blodget
 * CREATE DATE: 11/14/2018
 */

#include "md5.h"


int main(int argc, char *argv[])
{
    int ret;
    uint8_t *msg;
    uint8_t hash_str[33];

    if (argc==2)
    {
        msg = argv[1];
    }
    else
    {
        msg="The quick brown fox jumps over the lazy dog";
    }
    printf("usage: %s 'string'\n", argv[0]);

    md5(msg, hash_str);

    printf("msg = %s\n",msg);
    printf("hash_str = %s\n",hash_str);

    return 0;
}

